-- Flyway-style migration: add maize_patches and patch_id columns

CREATE TABLE IF NOT EXISTS maize_patches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farmer_profile_id BIGINT NOT NULL,
  year INTEGER NOT NULL,
  season VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  crop_type VARCHAR(100) NOT NULL,
  area DOUBLE PRECISION,
  area_unit VARCHAR(50),
  planting_date DATE,
  expected_harvest_date DATE,
  actual_harvest_date DATE,
  location VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

-- Add patch_id columns to existing tables (nullable for backfill)
ALTER TABLE IF EXISTS farm_activities ADD COLUMN IF NOT EXISTS patch_id BIGINT;
ALTER TABLE IF EXISTS farm_expenses ADD COLUMN IF NOT EXISTS patch_id BIGINT;
ALTER TABLE IF EXISTS yield_records ADD COLUMN IF NOT EXISTS patch_id BIGINT;
ALTER TABLE IF EXISTS input_usage_records ADD COLUMN IF NOT EXISTS patch_id BIGINT;

-- Optionally: add foreign key constraints after backfill
-- ALTER TABLE farm_activities ADD CONSTRAINT fk_activities_patch FOREIGN KEY (patch_id) REFERENCES maize_patches(id);
